### ISSUE TITLE
Datenmanagement Feedback

### ISSUE THREAD

**Issue by Fuenfgeld** [Fuenfgeld/TeamDataScDatenmanagementUndArchivierung#34]
Hi Zusammen wie versprochen nochmal der Feedback von Kerstin Stand letztes Wochenende:
3.1:
* die Erklärung ist etwas 'dünn' ausgefallen...--->
* hier benötigt man eine Referenz auf die zu erhebenden Datenelemente
3.2: FAIR gehört hier nicht hin, sondern ist die Summe aus allen Elementen des DMPs
3.3: sehr schön
3.4: Vergabe eines DOIs als persistenter Identifier während einer Publikation, Datensatz nach Dublin Core annotieren für eine Veröffentlichung

**Comment by AMB-Git-Hub** [comment]
@Fuenfgeld Beim Versuch des Erstellens der DOI in Zenodo wird die Freigabe durch den Besitzer des Repositories gefordert. Könntest du uns diese Rechte übertragen?

https://guides.github.com/activities/citable-code/

**Comment by ohoelske** [comment]
@AMB-Git-Hub @ahodelin @Fuenfgeld  : Please check this out:

[https://dataverse.harvard.edu/dataverse_homepage.xhtml](url)

Please register so that we can collaborate on our dataverse project. Here, we can deposit all datasets for archiving purposes. I've already deposited the .db file, which generated a DOI. We have to work on the metadata annotation. The standard Harvard Dataverse metatdata annotation is in accordance with the Dublin Core Metadata Initiative.

[https://dataverse.harvard.edu/dataverse/PRECOV](url)

Der DMP ist dementsprechend aktualisiert.

**Comment by AMB-Git-Hub** [comment]
We gerade besprochen, Dublin Core exemplarisch implementiert
